import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync,spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const script=fileURLToPath(new URL('../scripts/update-sync.mjs',import.meta.url));
test('Upstream review generates an engine-only patch without changing working tree, index or branch',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'forgeblog-updater-'));const git=(...args)=>execFileSync('git',args,{cwd:root,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();try{git('init');
// Pin end-of-line policy for this fixture repository. A developer machine with a global
// core.autocrlf=true (common on Windows) would otherwise rewrite every checked-out file to
// CRLF, making the byte-for-byte content assertions below fail for a reason unrelated to the
// update-review logic under test. The production script never changes git configuration.
git('config','core.autocrlf','false');git('config','core.eol','lf');
git('config','user.name','ForgeBlog test');git('config','user.email','test@example.test');const write=(p,text)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),text);};write('src/lib/core.ts','export const value=1;\n');write('src/config/site.json','{"name":"My brand"}\n');write('src/content/posts/my-story.md','Private content\n');write('public/media/image.txt','My image');git('add','.');git('commit','-m','initial');const original=git('rev-parse','HEAD');write('src/lib/core.ts','export const value=2;\n');write('src/config/site.json','{"name":"Wrong upstream brand"}\n');write('src/content/posts/my-story.md','Wrong replacement\n');write('public/media/image.txt','Wrong image');git('add','.');git('commit','-m','upstream');const target=git('rev-parse','HEAD');git('checkout','--detach',original);const result=spawnSync(process.execPath,[script,target],{cwd:root,encoding:'utf8'});assert.equal(result.status,0,result.stderr);assert.equal(git('rev-parse','HEAD'),original);assert.equal(git('diff','--name-only'),'');assert.equal(git('diff','--cached','--name-only'),'');const patch=fs.readFileSync(path.join(root,'.upstream-review/engine.patch'),'utf8');assert.ok(patch.includes('src/lib/core.ts'));assert.ok(!patch.includes('Wrong'));assert.equal(fs.readFileSync(path.join(root,'src/content/posts/my-story.md'),'utf8'),'Private content\n');assert.equal(JSON.parse(fs.readFileSync(path.join(root,'.upstream-review/review.json'))).mode,'REVIEW_ONLY');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('Update script refuses an option-like or shell-shaped upstream ref',()=>{for(const ref of ['--help','HEAD;echo hacked','../outside'])assert.notEqual(spawnSync(process.execPath,[script,ref],{encoding:'utf8'}).status,0);});
