export type ThemeCategory =
  "minimal" | "future" | "lifestyle" | "professional" | "creative" | "retro";
export type LayoutVariant =
  | "reading-first"
  | "grid-editorial"
  | "immersive-visual"
  | "future-interface"
  | "friendly-organic"
  | "experimental";
export interface ThemeDefinition {
  key: string;
  name: string;
  category: ThemeCategory;
  summary: string;
  idealFor: string;
  moods: string[];
  supportsDarkMode: boolean;
  supportsUserModeToggle: boolean;
  defaultMode: "light" | "dark";
  preview: { image: string; alt: string; accentSwatches: string[] };
  fonts: { heading: string; body: string; mono: string };
  features: {
    supportsImmersiveHero: boolean;
    supportsGridHomepage: boolean;
    supportsLargeMedia: boolean;
    supportsDecorativeMotion: boolean;
    preferredGalleryLayouts: string[];
  };
  tokensFile: string;
  layoutVariant: LayoutVariant;
  componentVariants: { card: string; header: string };
}
export const themeRegistry: ThemeDefinition[] = [
  {
    key: "minimal-editorial",
    name: "Minimal Editorial",
    category: "minimal",
    summary: "Letisztult ritmus, meleg papír, időtálló tipográfia.",
    idealFor: "minimal",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/coast.jpg",
      alt: "Minimal Editorial előnézet",
      accentSwatches: ["#234f43", "#fbfaf7", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/minimal-editorial.css",
    layoutVariant: "reading-first",
    componentVariants: {
      card: "reading-first",
      header: "reading-first",
    },
  },
  {
    key: "minimal-dark",
    name: "Minimal Dark",
    category: "minimal",
    summary: "Visszafogott, esti olvasásra hangolt felület.",
    idealFor: "minimal",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/demo/coast.jpg",
      alt: "Minimal Dark előnézet",
      accentSwatches: ["#bdd1c5", "#111a17", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/minimal-dark.css",
    layoutVariant: "reading-first",
    componentVariants: {
      card: "reading-first",
      header: "reading-first",
    },
  },
  {
    key: "swiss-grid",
    name: "Swiss Grid",
    category: "minimal",
    summary: "Határozott rács, fegyelmezett arányok.",
    idealFor: "minimal",
    moods: ["grid-editorial"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/architecture.jpg",
      alt: "Swiss Grid előnézet",
      accentSwatches: ["#c12622", "#f8f8f5", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/swiss-grid.css",
    layoutVariant: "grid-editorial",
    componentVariants: {
      card: "grid-editorial",
      header: "grid-editorial",
    },
  },
  {
    key: "soft-journal",
    name: "Soft Journal",
    category: "minimal",
    summary: "Személyes jegyzetek, lágy tónusok.",
    idealFor: "minimal",
    moods: ["friendly-organic"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/workspace.jpg",
      alt: "Soft Journal előnézet",
      accentSwatches: ["#875448", "#fbf5ef", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/soft-journal.css",
    layoutVariant: "friendly-organic",
    componentVariants: {
      card: "friendly-organic",
      header: "friendly-organic",
    },
  },
  {
    key: "brutalist",
    name: "Brutalist",
    category: "creative",
    summary: "Kontrasztos kontúrok, nyers szerkesztőségi karakter.",
    idealFor: "creative",
    moods: ["experimental"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/architecture.jpg",
      alt: "Brutalist előnézet",
      accentSwatches: ["#202020", "#f6f1d9", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/brutalist.css",
    layoutVariant: "experimental",
    componentVariants: {
      card: "experimental",
      header: "experimental",
    },
  },
  {
    key: "developer-console",
    name: "Developer Console",
    category: "future",
    summary: "Monospace rendszer fejlesztői történetekhez.",
    idealFor: "future",
    moods: ["future-interface"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/demo/workspace.jpg",
      alt: "Developer Console előnézet",
      accentSwatches: ["#aae1ae", "#101a16", "#c6b498"],
    },
    fonts: {
      heading: "monospace",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/developer-console.css",
    layoutVariant: "future-interface",
    componentVariants: {
      card: "future-interface",
      header: "future-interface",
    },
  },
  {
    key: "cyber-neon",
    name: "Cyber Neon",
    category: "future",
    summary: "Éjszakai kontraszt, visszafogott neon akcentus.",
    idealFor: "future",
    moods: ["future-interface"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/demo/harbor.jpg",
      alt: "Cyber Neon előnézet",
      accentSwatches: ["#9fecdb", "#141620", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/cyber-neon.css",
    layoutVariant: "future-interface",
    componentVariants: {
      card: "future-interface",
      header: "future-interface",
    },
  },
  {
    key: "glass-future",
    name: "Glass Future",
    category: "future",
    summary: "Rétegzett kártyák, tiszta digitális felület.",
    idealFor: "future",
    moods: ["future-interface"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/architecture.jpg",
      alt: "Glass Future előnézet",
      accentSwatches: ["#405a91", "#f1f4fa", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/glass-future.css",
    layoutVariant: "future-interface",
    componentVariants: {
      card: "future-interface",
      header: "future-interface",
    },
  },
  {
    key: "holographic",
    name: "Holographic",
    category: "future",
    summary: "Színváltó tónusok kreatív gondolatokhoz.",
    idealFor: "future",
    moods: ["experimental"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/sea-cave.jpg",
      alt: "Holographic előnézet",
      accentSwatches: ["#6d478d", "#f8f1fb", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/holographic.css",
    layoutVariant: "experimental",
    componentVariants: {
      card: "experimental",
      header: "experimental",
    },
  },
  {
    key: "ai-lab",
    name: "AI Lab",
    category: "future",
    summary: "Kutatási jegyzetek, átlátható információs hierarchia.",
    idealFor: "future",
    moods: ["future-interface"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/workspace.jpg",
      alt: "AI Lab előnézet",
      accentSwatches: ["#375e78", "#f0f5f7", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/ai-lab.css",
    layoutVariant: "future-interface",
    componentVariants: {
      card: "future-interface",
      header: "future-interface",
    },
  },
  {
    key: "travel-atlas",
    name: "Travel Atlas",
    category: "lifestyle",
    summary: "Helyek és történetek nagy képfelületekkel.",
    idealFor: "lifestyle",
    moods: ["immersive-visual"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/coast.jpg",
      alt: "Travel Atlas előnézet",
      accentSwatches: ["#315f6a", "#f7f4ed", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/travel-atlas.css",
    layoutVariant: "immersive-visual",
    componentVariants: {
      card: "immersive-visual",
      header: "immersive-visual",
    },
  },
  {
    key: "outdoor-expedition",
    name: "Outdoor Expedition",
    category: "lifestyle",
    summary: "Természetes színek a hegyek ritmusában.",
    idealFor: "lifestyle",
    moods: ["immersive-visual"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/alpine.jpg",
      alt: "Outdoor Expedition előnézet",
      accentSwatches: ["#485c36", "#f5f4eb", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/outdoor-expedition.css",
    layoutVariant: "immersive-visual",
    componentVariants: {
      card: "immersive-visual",
      header: "immersive-visual",
    },
  },
  {
    key: "food-journal",
    name: "Food Journal",
    category: "lifestyle",
    summary: "Meleg, ízes magazin receptekhez és történetekhez.",
    idealFor: "lifestyle",
    moods: ["friendly-organic"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/breakfast.jpg",
      alt: "Food Journal előnézet",
      accentSwatches: ["#914f31", "#fdf7ee", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/food-journal.css",
    layoutVariant: "friendly-organic",
    componentVariants: {
      card: "friendly-organic",
      header: "friendly-organic",
    },
  },
  {
    key: "recipe-studio",
    name: "Recipe Studio",
    category: "lifestyle",
    summary: "Jól kereshető, kényelmesen követhető receptek.",
    idealFor: "lifestyle",
    moods: ["grid-editorial"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/breakfast.jpg",
      alt: "Recipe Studio előnézet",
      accentSwatches: ["#577240", "#fafaf0", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/recipe-studio.css",
    layoutVariant: "grid-editorial",
    componentVariants: {
      card: "grid-editorial",
      header: "grid-editorial",
    },
  },
  {
    key: "photo-portfolio",
    name: "Photo Portfolio",
    category: "creative",
    summary: "A fényképek kerülnek előtérbe.",
    idealFor: "creative",
    moods: ["immersive-visual"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/demo/sunset-peaks.jpg",
      alt: "Photo Portfolio előnézet",
      accentSwatches: ["#e6e0d0", "#181a19", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/photo-portfolio.css",
    layoutVariant: "immersive-visual",
    componentVariants: {
      card: "immersive-visual",
      header: "immersive-visual",
    },
  },
  {
    key: "art-gallery",
    name: "Art Gallery",
    category: "creative",
    summary: "Sok levegő, galériaszerű elrendezés.",
    idealFor: "creative",
    moods: ["experimental"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/ceramics.jpg",
      alt: "Art Gallery előnézet",
      accentSwatches: ["#705950", "#faf6f0", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/art-gallery.css",
    layoutVariant: "experimental",
    componentVariants: {
      card: "experimental",
      header: "experimental",
    },
  },
  {
    key: "music-night",
    name: "Music Night",
    category: "creative",
    summary: "Sötét színpad, finom rózsaszín hangsúlyok.",
    idealFor: "creative",
    moods: ["immersive-visual"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/demo/harbor.jpg",
      alt: "Music Night előnézet",
      accentSwatches: ["#e6b6cd", "#20141d", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/music-night.css",
    layoutVariant: "immersive-visual",
    componentVariants: {
      card: "immersive-visual",
      header: "immersive-visual",
    },
  },
  {
    key: "gaming-arena",
    name: "Gaming Arena",
    category: "creative",
    summary: "Erős hierarchia, olvasható sötét felület.",
    idealFor: "creative",
    moods: ["future-interface"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/demo/forest.jpg",
      alt: "Gaming Arena előnézet",
      accentSwatches: ["#bad581", "#151c15", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/gaming-arena.css",
    layoutVariant: "future-interface",
    componentVariants: {
      card: "future-interface",
      header: "future-interface",
    },
  },
  {
    key: "corporate-authority",
    name: "Corporate Authority",
    category: "professional",
    summary: "Nyugodt, megbízható szakmai jelenlét.",
    idealFor: "professional",
    moods: ["grid-editorial"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/architecture.jpg",
      alt: "Corporate Authority előnézet",
      accentSwatches: ["#325771", "#f7f9fa", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/corporate-authority.css",
    layoutVariant: "grid-editorial",
    componentVariants: {
      card: "grid-editorial",
      header: "grid-editorial",
    },
  },
  {
    key: "industrial-workshop",
    name: "Industrial Workshop",
    category: "professional",
    summary: "Anyagszerű tónusok, precíz szerkesztés.",
    idealFor: "professional",
    moods: ["grid-editorial"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/workspace.jpg",
      alt: "Industrial Workshop előnézet",
      accentSwatches: ["#865126", "#f6f3ee", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/industrial-workshop.css",
    layoutVariant: "grid-editorial",
    componentVariants: {
      card: "grid-editorial",
      header: "grid-editorial",
    },
  },
  {
    key: "academic-paper",
    name: "Academic Paper",
    category: "professional",
    summary: "Olvasásközpontú, hivatkozásbarát felület.",
    idealFor: "professional",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/workspace.jpg",
      alt: "Academic Paper előnézet",
      accentSwatches: ["#384b6a", "#fffefa", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/academic-paper.css",
    layoutVariant: "reading-first",
    componentVariants: {
      card: "reading-first",
      header: "reading-first",
    },
  },
  {
    key: "magazine-newsroom",
    name: "Magazine Newsroom",
    category: "professional",
    summary: "Szerkesztőségi rács és karakteres címsorok.",
    idealFor: "professional",
    moods: ["grid-editorial"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/old-town.jpg",
      alt: "Magazine Newsroom előnézet",
      accentSwatches: ["#9c3737", "#faf8f4", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/magazine-newsroom.css",
    layoutVariant: "grid-editorial",
    componentVariants: {
      card: "grid-editorial",
      header: "grid-editorial",
    },
  },
  {
    key: "luxury-fashion",
    name: "Luxury Fashion",
    category: "creative",
    summary: "Nagyvonalú képek, meleg semleges paletta.",
    idealFor: "creative",
    moods: ["immersive-visual"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/ceramics.jpg",
      alt: "Luxury Fashion előnézet",
      accentSwatches: ["#6c5642", "#fbf8f2", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/luxury-fashion.css",
    layoutVariant: "immersive-visual",
    componentVariants: {
      card: "immersive-visual",
      header: "immersive-visual",
    },
  },
  {
    key: "nature-organic",
    name: "Nature Organic",
    category: "lifestyle",
    summary: "Organikus, természetközeli és nyugodt.",
    idealFor: "lifestyle",
    moods: ["friendly-organic"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/olive.jpg",
      alt: "Nature Organic előnézet",
      accentSwatches: ["#456c47", "#f5f7ed", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/nature-organic.css",
    layoutVariant: "friendly-organic",
    componentVariants: {
      card: "friendly-organic",
      header: "friendly-organic",
    },
  },
  {
    key: "family-storybook",
    name: "Family Storybook",
    category: "lifestyle",
    summary: "Otthonos, személyes emlékekhez.",
    idealFor: "lifestyle",
    moods: ["friendly-organic"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/breakfast.jpg",
      alt: "Family Storybook előnézet",
      accentSwatches: ["#865c47", "#fff7eb", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/family-storybook.css",
    layoutVariant: "friendly-organic",
    componentVariants: {
      card: "friendly-organic",
      header: "friendly-organic",
    },
  },
  {
    key: "retro-eighties",
    name: "Retro Eighties",
    category: "retro",
    summary: "Retro színpárok, mai használhatóság.",
    idealFor: "retro",
    moods: ["experimental"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/demo/sunset-peaks.jpg",
      alt: "Retro Eighties előnézet",
      accentSwatches: ["#805076", "#fbf2e3", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/retro-eighties.css",
    layoutVariant: "experimental",
    componentVariants: {
      card: "experimental",
      header: "experimental",
    },
  },
];
export const themes = themeRegistry;
export function getTheme(key: string): ThemeDefinition {
  const theme = themeRegistry.find((t) => t.key === key);
  if (!theme) throw new Error(`Unknown theme: ${key}`);
  return theme;
}
export const getThemeByKey = getTheme;
export const themeKeys = themeRegistry.map((t) => t.key);
