export type ThemeCategory =
  "minimal" | "future" | "lifestyle" | "professional" | "creative" | "retro";
export type LayoutVariant =
  | "reading-first"
  | "grid-editorial"
  | "immersive-visual"
  | "future-interface"
  | "friendly-organic"
  | "experimental";
export interface ThemeDefinition {
  key: string;
  name: string;
  category: ThemeCategory;
  summary: string;
  idealFor: string;
  moods: string[];
  supportsDarkMode: boolean;
  supportsUserModeToggle: boolean;
  defaultMode: "light" | "dark";
  preview: { image: string; alt: string; accentSwatches: string[] };
  fonts: { heading: string; body: string; mono: string };
  features: {
    supportsImmersiveHero: boolean;
    supportsGridHomepage: boolean;
    supportsLargeMedia: boolean;
    supportsDecorativeMotion: boolean;
    preferredGalleryLayouts: string[];
  };
  tokensFile: string;
  layoutVariant: LayoutVariant;
  componentVariants: { card: string; header: string };
}
export const themeRegistry: ThemeDefinition[] = [
  {
    key: "minimal-editorial",
    name: "Minimal Editorial",
    category: "minimal",
    summary: "Letisztult ritmus, meleg papír, időtálló tipográfia.",
    idealFor: "minimal",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/6RqSDGaNJ5c.webp",
      alt: "Minimal Editorial előnézet",
      accentSwatches: ["#234f43", "#fbfaf7", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/minimal-editorial.css",
    layoutVariant: "reading-first",
    componentVariants: {
      card: "reading-first",
      header: "reading-first",
    },
  },
  {
    key: "minimal-dark",
    name: "Minimal Dark",
    category: "minimal",
    summary: "Visszafogott, esti olvasásra hangolt felület.",
    idealFor: "minimal",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/catalog/6RqSDGaNJ5c.webp",
      alt: "Minimal Dark előnézet",
      accentSwatches: ["#bdd1c5", "#111a17", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/minimal-dark.css",
    layoutVariant: "reading-first",
    componentVariants: {
      card: "reading-first",
      header: "reading-first",
    },
  },
  {
    key: "swiss-grid",
    name: "Swiss Grid",
    category: "minimal",
    summary: "Határozott rács, fegyelmezett arányok.",
    idealFor: "minimal",
    moods: ["grid-editorial"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/DaQR-GafxYw.webp",
      alt: "Swiss Grid előnézet",
      accentSwatches: ["#c12622", "#f8f8f5", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/swiss-grid.css",
    layoutVariant: "grid-editorial",
    componentVariants: {
      card: "grid-editorial",
      header: "grid-editorial",
    },
  },
  {
    key: "soft-journal",
    name: "Soft Journal",
    category: "minimal",
    summary: "Személyes jegyzetek, lágy tónusok.",
    idealFor: "minimal",
    moods: ["friendly-organic"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/6RqSDGaNJ5c.webp",
      alt: "Soft Journal előnézet",
      accentSwatches: ["#875448", "#fbf5ef", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/soft-journal.css",
    layoutVariant: "friendly-organic",
    componentVariants: {
      card: "friendly-organic",
      header: "friendly-organic",
    },
  },
  {
    key: "brutalist",
    name: "Brutalist",
    category: "creative",
    summary: "Kontrasztos kontúrok, nyers szerkesztőségi karakter.",
    idealFor: "creative",
    moods: ["experimental"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/DaQR-GafxYw.webp",
      alt: "Brutalist előnézet",
      accentSwatches: ["#202020", "#f6f1d9", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/brutalist.css",
    layoutVariant: "experimental",
    componentVariants: {
      card: "experimental",
      header: "experimental",
    },
  },
  {
    key: "developer-console",
    name: "Developer Console",
    category: "future",
    summary: "Monospace rendszer fejlesztői történetekhez.",
    idealFor: "future",
    moods: ["future-interface"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/catalog/6RqSDGaNJ5c.webp",
      alt: "Developer Console előnézet",
      accentSwatches: ["#aae1ae", "#101a16", "#c6b498"],
    },
    fonts: {
      heading: "monospace",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/developer-console.css",
    layoutVariant: "future-interface",
    componentVariants: {
      card: "future-interface",
      header: "future-interface",
    },
  },
  {
    key: "cyber-neon",
    name: "Cyber Neon",
    category: "future",
    summary: "Éjszakai kontraszt, visszafogott neon akcentus.",
    idealFor: "future",
    moods: ["future-interface"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/catalog/6RqSDGaNJ5c.webp",
      alt: "Cyber Neon előnézet",
      accentSwatches: ["#9fecdb", "#141620", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/cyber-neon.css",
    layoutVariant: "future-interface",
    componentVariants: {
      card: "future-interface",
      header: "future-interface",
    },
  },
  {
    key: "glass-future",
    name: "Glass Future",
    category: "future",
    summary: "Rétegzett kártyák, tiszta digitális felület.",
    idealFor: "future",
    moods: ["future-interface"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/DaQR-GafxYw.webp",
      alt: "Glass Future előnézet",
      accentSwatches: ["#405a91", "#f1f4fa", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/glass-future.css",
    layoutVariant: "future-interface",
    componentVariants: {
      card: "future-interface",
      header: "future-interface",
    },
  },
  {
    key: "holographic",
    name: "Holographic",
    category: "future",
    summary: "Színváltó tónusok kreatív gondolatokhoz.",
    idealFor: "future",
    moods: ["experimental"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/TjegK_z-0j8.webp",
      alt: "Holographic előnézet",
      accentSwatches: ["#6d478d", "#f8f1fb", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/holographic.css",
    layoutVariant: "experimental",
    componentVariants: {
      card: "experimental",
      header: "experimental",
    },
  },
  {
    key: "ai-lab",
    name: "AI Lab",
    category: "future",
    summary: "Kutatási jegyzetek, átlátható információs hierarchia.",
    idealFor: "future",
    moods: ["future-interface"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/6RqSDGaNJ5c.webp",
      alt: "AI Lab előnézet",
      accentSwatches: ["#375e78", "#f0f5f7", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/ai-lab.css",
    layoutVariant: "future-interface",
    componentVariants: {
      card: "future-interface",
      header: "future-interface",
    },
  },
  {
    key: "travel-atlas",
    name: "Travel Atlas",
    category: "lifestyle",
    summary: "Helyek és történetek nagy képfelületekkel.",
    idealFor: "lifestyle",
    moods: ["immersive-visual"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/6RqSDGaNJ5c.webp",
      alt: "Travel Atlas előnézet",
      accentSwatches: ["#315f6a", "#f7f4ed", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/travel-atlas.css",
    layoutVariant: "immersive-visual",
    componentVariants: {
      card: "immersive-visual",
      header: "immersive-visual",
    },
  },
  {
    key: "outdoor-expedition",
    name: "Outdoor Expedition",
    category: "lifestyle",
    summary: "Természetes színek a hegyek ritmusában.",
    idealFor: "lifestyle",
    moods: ["immersive-visual"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/7VotVatHM7Q.webp",
      alt: "Outdoor Expedition előnézet",
      accentSwatches: ["#485c36", "#f5f4eb", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/outdoor-expedition.css",
    layoutVariant: "immersive-visual",
    componentVariants: {
      card: "immersive-visual",
      header: "immersive-visual",
    },
  },
  {
    key: "food-journal",
    name: "Food Journal",
    category: "lifestyle",
    summary: "Meleg, ízes magazin receptekhez és történetekhez.",
    idealFor: "lifestyle",
    moods: ["friendly-organic"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/TD4DBagg2wE.webp",
      alt: "Food Journal előnézet",
      accentSwatches: ["#914f31", "#fdf7ee", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/food-journal.css",
    layoutVariant: "friendly-organic",
    componentVariants: {
      card: "friendly-organic",
      header: "friendly-organic",
    },
  },
  {
    key: "recipe-studio",
    name: "Recipe Studio",
    category: "lifestyle",
    summary: "Jól kereshető, kényelmesen követhető receptek.",
    idealFor: "lifestyle",
    moods: ["grid-editorial"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/TD4DBagg2wE.webp",
      alt: "Recipe Studio előnézet",
      accentSwatches: ["#577240", "#fafaf0", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/recipe-studio.css",
    layoutVariant: "grid-editorial",
    componentVariants: {
      card: "grid-editorial",
      header: "grid-editorial",
    },
  },
  {
    key: "photo-portfolio",
    name: "Photo Portfolio",
    category: "creative",
    summary: "A fényképek kerülnek előtérbe.",
    idealFor: "creative",
    moods: ["immersive-visual"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/catalog/7VotVatHM7Q.webp",
      alt: "Photo Portfolio előnézet",
      accentSwatches: ["#e6e0d0", "#181a19", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/photo-portfolio.css",
    layoutVariant: "immersive-visual",
    componentVariants: {
      card: "immersive-visual",
      header: "immersive-visual",
    },
  },
  {
    key: "art-gallery",
    name: "Art Gallery",
    category: "creative",
    summary: "Sok levegő, galériaszerű elrendezés.",
    idealFor: "creative",
    moods: ["experimental"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/6RqSDGaNJ5c.webp",
      alt: "Art Gallery előnézet",
      accentSwatches: ["#705950", "#faf6f0", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/art-gallery.css",
    layoutVariant: "experimental",
    componentVariants: {
      card: "experimental",
      header: "experimental",
    },
  },
  {
    key: "music-night",
    name: "Music Night",
    category: "creative",
    summary: "Sötét színpad, finom rózsaszín hangsúlyok.",
    idealFor: "creative",
    moods: ["immersive-visual"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/catalog/6RqSDGaNJ5c.webp",
      alt: "Music Night előnézet",
      accentSwatches: ["#e6b6cd", "#20141d", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/music-night.css",
    layoutVariant: "immersive-visual",
    componentVariants: {
      card: "immersive-visual",
      header: "immersive-visual",
    },
  },
  {
    key: "gaming-arena",
    name: "Gaming Arena",
    category: "creative",
    summary: "Erős hierarchia, olvasható sötét felület.",
    idealFor: "creative",
    moods: ["future-interface"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/catalog/AjJCGAIUcqo.webp",
      alt: "Gaming Arena előnézet",
      accentSwatches: ["#bad581", "#151c15", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/gaming-arena.css",
    layoutVariant: "future-interface",
    componentVariants: {
      card: "future-interface",
      header: "future-interface",
    },
  },
  {
    key: "corporate-authority",
    name: "Corporate Authority",
    category: "professional",
    summary: "Nyugodt, megbízható szakmai jelenlét.",
    idealFor: "professional",
    moods: ["grid-editorial"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/DaQR-GafxYw.webp",
      alt: "Corporate Authority előnézet",
      accentSwatches: ["#325771", "#f7f9fa", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/corporate-authority.css",
    layoutVariant: "grid-editorial",
    componentVariants: {
      card: "grid-editorial",
      header: "grid-editorial",
    },
  },
  {
    key: "industrial-workshop",
    name: "Industrial Workshop",
    category: "professional",
    summary: "Anyagszerű tónusok, precíz szerkesztés.",
    idealFor: "professional",
    moods: ["grid-editorial"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/6RqSDGaNJ5c.webp",
      alt: "Industrial Workshop előnézet",
      accentSwatches: ["#865126", "#f6f3ee", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/industrial-workshop.css",
    layoutVariant: "grid-editorial",
    componentVariants: {
      card: "grid-editorial",
      header: "grid-editorial",
    },
  },
  {
    key: "academic-paper",
    name: "Academic Paper",
    category: "professional",
    summary: "Olvasásközpontú, hivatkozásbarát felület.",
    idealFor: "professional",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/6RqSDGaNJ5c.webp",
      alt: "Academic Paper előnézet",
      accentSwatches: ["#384b6a", "#fffefa", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/academic-paper.css",
    layoutVariant: "reading-first",
    componentVariants: {
      card: "reading-first",
      header: "reading-first",
    },
  },
  {
    key: "magazine-newsroom",
    name: "Magazine Newsroom",
    category: "professional",
    summary: "Szerkesztőségi rács és karakteres címsorok.",
    idealFor: "professional",
    moods: ["grid-editorial"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/6RqSDGaNJ5c.webp",
      alt: "Magazine Newsroom előnézet",
      accentSwatches: ["#9c3737", "#faf8f4", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/magazine-newsroom.css",
    layoutVariant: "grid-editorial",
    componentVariants: {
      card: "grid-editorial",
      header: "grid-editorial",
    },
  },
  {
    key: "luxury-fashion",
    name: "Luxury Fashion",
    category: "creative",
    summary: "Nagyvonalú képek, meleg semleges paletta.",
    idealFor: "creative",
    moods: ["immersive-visual"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/6RqSDGaNJ5c.webp",
      alt: "Luxury Fashion előnézet",
      accentSwatches: ["#6c5642", "#fbf8f2", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/luxury-fashion.css",
    layoutVariant: "immersive-visual",
    componentVariants: {
      card: "immersive-visual",
      header: "immersive-visual",
    },
  },
  {
    key: "nature-organic",
    name: "Nature Organic",
    category: "lifestyle",
    summary: "Organikus, természetközeli és nyugodt.",
    idealFor: "lifestyle",
    moods: ["friendly-organic"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/ApkZ5RTza5g.webp",
      alt: "Nature Organic előnézet",
      accentSwatches: ["#456c47", "#f5f7ed", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/nature-organic.css",
    layoutVariant: "friendly-organic",
    componentVariants: {
      card: "friendly-organic",
      header: "friendly-organic",
    },
  },
  {
    key: "family-storybook",
    name: "Family Storybook",
    category: "lifestyle",
    summary: "Otthonos, személyes emlékekhez.",
    idealFor: "lifestyle",
    moods: ["friendly-organic"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/TD4DBagg2wE.webp",
      alt: "Family Storybook előnézet",
      accentSwatches: ["#865c47", "#fff7eb", "#c6b498"],
    },
    fonts: {
      heading: "Georgia",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/family-storybook.css",
    layoutVariant: "friendly-organic",
    componentVariants: {
      card: "friendly-organic",
      header: "friendly-organic",
    },
  },
  {
    key: "retro-eighties",
    name: "Retro Eighties",
    category: "retro",
    summary: "Retro színpárok, mai használhatóság.",
    idealFor: "retro",
    moods: ["experimental"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/catalog/7VotVatHM7Q.webp",
      alt: "Retro Eighties előnézet",
      accentSwatches: ["#805076", "#fbf2e3", "#c6b498"],
    },
    fonts: {
      heading: "Arial",
      body: "system-ui",
      mono: "monospace",
    },
    features: {
      supportsImmersiveHero: false,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry"],
    },
    tokensFile: "/src/styles/themes/retro-eighties.css",
    layoutVariant: "experimental",
    componentVariants: {
      card: "experimental",
      header: "experimental",
    },
  },
  {
    key: "forest-walks",
    name: "Forest Walks",
    category: "lifestyle",
    summary: "Mély erdőzöld, meleg fa tónusok.",
    idealFor: "nature",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Forest Walks előnézet",
      accentSwatches: ["#2f5233", "#f4f1ea", "#c6b498"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/forest-walks.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "ocean-breeze",
    name: "Ocean Breeze",
    category: "lifestyle",
    summary: "Óceánkék, homokos krémszín.",
    idealFor: "travel",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Ocean Breeze előnézet",
      accentSwatches: ["#1f6f8b", "#f2f7fa", "#7ec3dc"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/ocean-breeze.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "terracotta-sunset",
    name: "Terracotta Sunset",
    category: "lifestyle",
    summary: "Meleg terrakotta, krémszín.",
    idealFor: "food",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Terracotta Sunset előnézet",
      accentSwatches: ["#9e4a2c", "#faf1e9", "#e08a63"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/terracotta-sunset.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "lavender-mist",
    name: "Lavender Mist",
    category: "minimal",
    summary: "Lágy levendula, fehér.",
    idealFor: "minimal",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Lavender Mist előnézet",
      accentSwatches: ["#6b5b95", "#f7f5fb", "#b3a3d8"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/lavender-mist.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "midnight-navy",
    name: "Midnight Navy",
    category: "professional",
    summary: "Sötét sötétkék, arany akcentus.",
    idealFor: "professional",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Midnight Navy előnézet",
      accentSwatches: ["#1b3a5c", "#c7a252", "#0c1219"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/midnight-navy.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "sage-garden",
    name: "Sage Garden",
    category: "lifestyle",
    summary: "Zsályazöld, törtfehér.",
    idealFor: "wellness",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Sage Garden előnézet",
      accentSwatches: ["#5c6f4d", "#f5f6f0", "#b8c99e"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/sage-garden.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "rose-quartz",
    name: "Rose Quartz",
    category: "lifestyle",
    summary: "Lágy rózsaszín, krémszín.",
    idealFor: "lifestyle",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Rose Quartz előnézet",
      accentSwatches: ["#8a4c5e", "#fbf4f5", "#d39aa8"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/rose-quartz.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "charcoal-studio",
    name: "Charcoal Studio",
    category: "professional",
    summary: "Faszénszürke, narancs akcentus.",
    idealFor: "portfolio",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Charcoal Studio előnézet",
      accentSwatches: ["#3a3a3a", "#e07b39", "#f2f2f1"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/charcoal-studio.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "sky-paper",
    name: "Sky Paper",
    category: "minimal",
    summary: "Világoskék, fehér papír.",
    idealFor: "minimal",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Sky Paper előnézet",
      accentSwatches: ["#3a7ca5", "#f3f7fa", "#85b6d4"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/sky-paper.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "golden-hour",
    name: "Golden Hour",
    category: "lifestyle",
    summary: "Meleg arany, barna.",
    idealFor: "photography",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Golden Hour előnézet",
      accentSwatches: ["#7c5c1e", "#faf4e8", "#d6ad5e"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/golden-hour.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "ink-and-paper",
    name: "Ink and Paper",
    category: "minimal",
    summary: "Fekete tinta, fehér papír.",
    idealFor: "writing",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Ink and Paper előnézet",
      accentSwatches: ["#111111", "#ffffff", "#555555"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/ink-and-paper.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "moss-stone",
    name: "Moss Stone",
    category: "lifestyle",
    summary: "Mohazöld, kőszürke.",
    idealFor: "nature",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Moss Stone előnézet",
      accentSwatches: ["#5b6b4f", "#f4f5f1", "#a5bb8f"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/moss-stone.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "coral-reef",
    name: "Coral Reef",
    category: "creative",
    summary: "Korall, türkiz.",
    idealFor: "creative",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Coral Reef előnézet",
      accentSwatches: ["#b3442e", "#faf5f3", "#7ec4bd"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/coral-reef.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "mono-terminal",
    name: "Mono Terminal",
    category: "future",
    summary: "Monokróm, terminálzöld.",
    idealFor: "developer",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "dark",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Mono Terminal előnézet",
      accentSwatches: ["#0f7a3d", "#0d0d0d", "#3ddc84"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/mono-terminal.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
  {
    key: "warm-library",
    name: "Warm Library",
    category: "professional",
    summary: "Meleg barna, krémszín.",
    idealFor: "editorial",
    moods: ["reading-first"],
    supportsDarkMode: true,
    supportsUserModeToggle: true,
    defaultMode: "light",
    preview: {
      image: "/media/stock/stock-0.jpg",
      alt: "Warm Library előnézet",
      accentSwatches: ["#6b4f2a", "#f7f3ec", "#c9a56a"],
    },
    fonts: { heading: "Georgia", body: "system-ui", mono: "monospace" },
    features: {
      supportsImmersiveHero: true,
      supportsGridHomepage: true,
      supportsLargeMedia: true,
      supportsDecorativeMotion: false,
      preferredGalleryLayouts: ["editorial-grid", "masonry", "stacked"],
    },
    tokensFile: "/src/styles/themes/warm-library.css",
    layoutVariant: "reading-first",
    componentVariants: { card: "reading-first", header: "reading-first" },
  },
];
export const themes = themeRegistry;
export function getTheme(key: string): ThemeDefinition {
  const theme = themeRegistry.find((t) => t.key === key);
  if (!theme) throw new Error(`Unknown theme: ${key}`);
  return theme;
}
export const getThemeByKey = getTheme;
export const themeKeys = themeRegistry.map((t) => t.key);
