// Local diagnostic fixture host only, never a production API or OAuth environment.
if(process.env.NODE_ENV === 'production' || process.env.GITHUB_CLIENT_SECRET || process.env.SESSION_SECRET) throw new Error('Diagnostic preview refuses production mode or live credentials.');
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import http from 'node:http';import {environment,serialize} from './runtime.mjs';
const root=path.resolve(fileURLToPath(new URL('../../',import.meta.url)));const pages=path.join(root,'src/pages');const routes=new Map();const port=Number(process.env.PORT||4321);
async function walk(dir){for(const ent of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,ent.name);if(ent.isDirectory()){await walk(file);continue;}if(!/\.(astro|ts)$/.test(file))continue;const name=path.relative(pages,file).replace(/\\/g,'/');let route='/'+name.replace(/\.(astro|ts)$/,'').replace(/(^|\/)index$/,'$1');if(file.endsWith('.astro')&&!route.endsWith('/'))route+='/';const mod=await import(pathToFileURL(file));if(route.includes('[')){if(!mod.getStaticPaths)throw new Error(`Missing getStaticPaths: ${file}`);for(const entry of await mod.getStaticPaths()){let url=route.replace(/\[([^\]]+)\]/g,(_,key)=>entry.params[key]);routes.set(url,{mod,props:entry.props||{},params:entry.params});}}else routes.set(route,{mod,props:{},params:{}});}}
await environment.run({url:new URL('http://localhost:'+port)},()=>walk(pages));
let css=fs.readFileSync(path.join(root,'src/styles/global.css'),'utf8').replace(/@import[^;]*;/g,'').replace(/@theme inline\s*\{[^}]*\}/g,'');css=fs.readFileSync(path.join(root,'node_modules/tailwindcss/preflight.css'),'utf8')+'\n'+css;css+=fs.readdirSync(path.join(root,'src/styles/themes')).filter(n=>n.endsWith('.css')).map(n=>fs.readFileSync(path.join(root,'src/styles/themes',n),'utf8')).join('\n');
const types={'.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.jpg':'image/jpeg','.webp':'image/webp','.json':'application/json','.png':'image/png','.ico':'image/x-icon','.txt':'text/plain'};
const server=http.createServer(async(req,res)=>{
// Diagnostic set_content documents have an opaque origin. This header is NOT production configuration.
res.setHeader('Access-Control-Allow-Origin','null');
try{const url=new URL(req.url,'http://localhost:'+port);if(url.pathname==='/__qa/styles.css'){res.writeHead(200,{'Content-Type':'text/css'});res.end(css);return;}if(url.pathname==='/__qa/workspace.js'){const file=path.join(root,'.qa/workspace.js');if(fs.existsSync(file)){res.writeHead(200,{'Content-Type':'text/javascript'});res.end(fs.readFileSync(file));return;}throw new Error('Run scripts/qa/bundle.mjs first.');}
if(url.pathname==='/api/creator'){const apiFile=path.join(root,'api/creator.ts');if(fs.existsSync(apiFile)){const {default:handler}=await import(pathToFileURL(apiFile));req.query=Object.fromEntries(url.searchParams);req.body=await new Promise(resolve=>{let raw='';req.on('data',chunk=>{raw+=chunk;if(raw.length>4500000)req.destroy();});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{});}catch{resolve(null);}});});res.status=n=>{res.statusCode=n;return res;};res.json=data=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data));};return await handler(req,res);}res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({configured:false,authenticated:false}));return;}
const file=path.resolve(root,'public','.'+decodeURIComponent(url.pathname));if(file.startsWith(path.join(root,'public')+path.sep)&&fs.existsSync(file)&&fs.statSync(file).isFile()){res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(fs.readFileSync(file));return;}
let route=routes.get(url.pathname);if(!route&&!path.extname(url.pathname)&&!url.pathname.endsWith('/')&&routes.has(url.pathname+'/')){res.writeHead(308,{Location:url.pathname+'/'+url.search});res.end();return;}const missing=!route;if(!route)route=routes.get('/404/');await environment.run({url,params:route.params,request:new Request(url)},async()=>{if(route.mod.GET){const response=await route.mod.GET({url,params:route.params});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(await response.text());return;}const rendered=await route.mod.default(route.props);if(rendered?.redirect){res.writeHead(rendered.status,{Location:rendered.redirect});res.end();return;}const html=await serialize(rendered);res.writeHead(missing?404:200,{'Content-Type':'text/html; charset=utf-8','X-ForgeBlog-QA':'Compatibility renderer; not Astro production'});res.end('<!doctype html>'+html);});}catch(error){console.error(req.url,error);if(!res.headersSent)res.writeHead(500,{'Content-Type':'text/plain; charset=utf-8'});res.end(String(error.stack||error));}});
server.listen(port,'127.0.0.1',()=>console.log(`DIAGNOSTIC COMPATIBILITY PREVIEW http://localhost:${port} — ${routes.size} routes. NOT ASTRO BUILD.`));
